@startuml BandaClasesUml

class Banda {
    Instrumentos : List<Instrumento>
    Integrantes : List<Musico>

    void generarIntegrantes()
    string afinarInstrumentos()
    string tocarInstrumentos()
}

interface Instrumento {
  void afinarInstrumento()
}

class InstrumentoCuerda {
  nombreInstrumento : string

  void afinarInstrumento()
}

class InstrumentoViento {
  nombreInstrumento : string

  void afinarInstrumento()
}

class InstrumentoPercusion {
  nombreInstrumento : string

  void afinarInstrumento()
}

class InstrumentoElectrico{
  nombreInstrumento : string

  void afinarInstrumento()
}

enum NombresMusicos {
  CARLOS
  ANDREA
  LUIS
  MARTA
  DIEGO
  ANA
  JORGE
  SOFIA
  PEDRO
  LAURA
}

class Musico {
  Nombre : string
  void tocarInstrumento(instrumento Instrumento)
}

enum InstrumentosCuerda{
  Guitarra
  Violín
  Arpa
  Bajo
  Ukelele
  Mandolina
}

enum InstrumentosViento{
  Flauta
  Saxofón
  Trompeta
  Clarinete
  Oboe
  Trombón
}

enum InstrumentosPercusion{
  Batería
  Timbal
  Cajón
  Bongos
  Marimba
  Pandereta
}

enum InstrumentosElectrico{
  Guitarra Eléctrica
  Bajo Eléctrico
  Teclado
  Sintetizadors
  Theremín
  Piano Eléctrico
}



Banda o-- Musico
Banda o-- Instrumento
Musico <-- NombresMusicos
Instrumento <|.. Musico
Instrumento <|.. InstrumentoCuerda
Instrumento <|.. InstrumentoViento
Instrumento <|.. InstrumentoPercusion
Instrumento <|.. InstrumentoElectrico
InstrumentoElectrico <-- InstrumentosElectrico
InstrumentoCuerda <-- InstrumentosCuerda
InstrumentoViento <-- InstrumentosViento
InstrumentoPercusion <-- InstrumentosPercusion

@enduml