@startuml BandaSecuenciaUML

Banda -> Musico ++: generarIntegrantes()
Musico -> NombresMusicos ++: Musico()
return nombreRandom
return listaMusicos[i] = musico
Banda -> Instrumento ++: generarInstrumento()
Instrumento -> enumInstrumentos ++: Instrumento()
return instrumentoRandom
return ListaInstrumentos[i] = instrumento

Banda -> Musico ++: afinarInstrumentos()
Musico -> Instrumento++: afinar()
return "Instrumento afinado"
return "El musico afino instrumento"

Banda -> Musico ++: tocarInstrumentos()
Musico -> Instrumento++: tocar()
return "Instrumento tocandose"
return "El musico esta tocando el instrumento"


@enduml